### ISSUE TITLE
Problem trying to make it work.

### ISSUE THREAD

**Issue by danielfilho** [monteslu/bean-io#4]
I've been struggling for a couple hours trying to find out what could be this error, but I just can't.

I've uploaded the [firmata](https://raw.githubusercontent.com/jacobrosenthal/arduino/bean/examples/StandardFirmata/StandardFirmata.ino) from Jacob Rosenthal, uploaded (it gave me an error, but on LightBlue Bean some ppl say it's ok). It appears linked on my Loader (see Sketch:firmata):

![screen shot 2014-12-23 at 18 12 22](https://cloud.githubusercontent.com/assets/24597/5542581/41a05e34-8acf-11e4-9899-111e165d41b3.png)

Then, I'm trying to run the "hello world" with the following code:

``` js
var beanio = require("bean-io");
var board = new beanio.Board({
  timeout: 30000 //optional - defaults to 30 seconds
  // uuid: 'myUuid' //optional - will use first bean found
});

board.on("ready", function() {
  console.log("CONNECTED");
  this.pinMode(13, this.MODES.OUTPUT);

  var byte = 0;

  // This will "blink" the on board led
  setInterval(function() {
    this.digitalWrite(13, (byte ^= 1));
  }.bind(this), 500);
});
```

but it gives me the following:

``` sh
Scanning for BLE devices...
(scan)found:Bean 2 9ac2b27b3cdf4423a0b8638e97ceba2f
Stop Scanning for BLE devices...
connect bean 9ac2b27b3cdf4423a0b8638e97ceba2f
TypeError: Cannot call method 'discoverCharacteristics' of undefined
    at new Bean (/Users/danielfilho/dev/github/danielfilho/bean-io/node_modules/bean-io/node_modules/ble-bean/lib/bean.js:27:11)
    at /Users/danielfilho/dev/github/danielfilho/bean-io/node_modules/bean-io/lib/bean.js:31:30
    at Peripheral.<anonymous> (/Users/danielfilho/dev/github/danielfilho/bean-io/node_modules/bean-io/node_modules/noble/lib/peripheral.js:66:7)
    at Peripheral.g (events.js:180:16)
    at Peripheral.emit (events.js:95:17)
    at Noble.onServicesDiscover (/Users/danielfilho/dev/github/danielfilho/bean-io/node_modules/bean-io/node_modules/noble/lib/noble.js:198:16)
    at emit (events.js:98:17)
    at nobleBindings.discoverIncludedServices.args.kCBMsgArgDeviceUUID (/Users/danielfilho/dev/github/danielfilho/bean-io/node_modules/bean-io/node_modules/noble/lib/mac/mavericks.js:234:8)
    at emit (events.js:95:17)
    at nobleBindings.sendCBMsg.sendXpcMessage.kCBMsgId (/Users/danielfilho/dev/github/danielfilho/bean-io/node_modules/bean-io/node_modules/noble/lib/mac/mavericks.js:41:8)
```

I've `npm install --save-dev johnny-five bean-io` it. any idea?

ps: I've installed `johnny-five`, although I'm not using it yet. I want to run the basic to go through it later.

**Comment by monteslu** [comment]
give version bean-io version 0.2.0 a spin

**Comment by danielfilho** [comment]
oh, I'm in US now and without my gadgets. in a couple weeks I'll give it a try.

thanks so far :)
