### ISSUE TITLE
Cannot connect -- Device or Firmware Error

### ISSUE THREAD

**Issue by jacobroufa** [monteslu/bean-io#7]
I can't seem to connect to my bean. I have loaded the Standard Firmata altered for Bean and that went just fine. LED on-board blinked when complete and success messages all around from the Loader and Arduino apps.

I have the following code:
```javascript
var five = require( 'johnny-five' );
var bean = require( 'bean-io' );

var myBean = new bean.Board();

var board = new five.Board({
  io: myBean
});

board.on( 'ready', function() {
  console.log( 'connected' );
  //var led = new five.Led({ pin: 13 });
  //led.blink();
});
```

Which produces the following output:
```
1423578301219 Device(s) bean
set color undefined
writing buffer: <Buffer f9>
writing buffer: <Buffer f0 79 f7>
1423578315255 Device or Firmware Error A timeout occurred while connecting to the Board.
Please check that you've properly flashed the board with the correct firmware.

TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Board.emit (events.js:74:15)
    at Board.<anonymous> (/Users/jacobroufa/Repos/beanTest/node_modules/johnny-five/lib/board.js:377:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by vizkits** [comment]
I have the following errors with bean-io@0.2.0, johnny-five@0.8.74 and io.js@1.6.3.

1431667000501 Device(s) bean 
1431667011329 Connected Firmata 
set color undefined
writing buffer: <Buffer f9>
writing buffer: <Buffer f0 79 f7>
1431667021332 Device or Firmware Error A timeout occurred while connecting to the Board. 

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting 
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: A timeout occurred while connecting to the Board.
    at Board.<anonymous> (/Users/chiena/projects/electron/node_modules/johnny-five/lib/board.js:405:26)
    at Timer.listOnTimeout (timers.js:89:15)

Any help will be appreciated! Thanks!

**Comment by Shaolin23** [comment]
Having same issue - Any luck figuring this out? Thanks!

**Comment by melboo** [comment]
Same issue. Anybody an idea?



```
1479782556765 Device or Firmware Error A timeout occurred while connecting to the Board. 
Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting

If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again.  

TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Board.EventEmitter.emit (events.js:74:15)
    at Board.log (/Users/melbo/Documents/Node/bean-io/node_modules/johnny-five/lib/board.js:630:8)
    at Board.(anonymous function) [as error] (/Users/melbo/Documents/Node/bean-io/node_modules/johnny-five/lib/board.js:641:14)
    at Board.<anonymous> (/Users/melbo/Documents/Node/bean-io/node_modules/johnny-five/lib/board.js:390:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by aminatamima** [comment]
Same issue, could anyone help please ? 

`1497008955401 Device or Firmware Error A timeout occurred while connecting to the Board.

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting

If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again.
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Board.emit (events.js:163:17)
    at Board.log (C:\Users\*****\node_modules\johnny-five\lib\board.js:635:8)
    at Board.(anonymous function) [as error] (C:\Users\******\node_modules\johnny-five\lib\board.js:646:14)
    at Board.<anonymous> (C:\Users\********\node_modules\johnny-five\lib\board.js:390:14)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)`
